### ISSUE TITLE
ERROR wrap_plonk_bn254: Failed to run `docker run`

### ISSUE THREAD

**Issue by hu55a1n1** [succinctlabs/sp1#1746] opened 2024-11-04 14:57 UTC
Hi all! 

I get this error when I try the plonk prover for the fibonacci example -> 
```
$ RUST_LOG=info cargo run --release -- --prove
# ...

2024-11-04T11:59:58.184458Z  INFO wrap_bn254: close time.busy=157s time.idle=1.42µs
[sp1] plonk circuit artifacts for version v3.0.0 do not exist at /Users/me/.sp1/circuits/plonk/v3.0.0. downloading...
  [00:02:55] [#####################################################################################################################################] 1.07 GiB/1.07 GiB (6.22 MiB/s, 0s)[sp1] downloaded https://sp1-circuits.s3-us-east-2.amazonaws.com/v3.0.0-plonk.tar.gz to "/Users/me/.sp1/circuits/plonk/v3.0.0"
2024-11-04T12:02:55.479318Z  INFO wrap_plonk_bn254: Running prove in docker
Unable to find image 'ghcr.io/succinctlabs/sp1-gnark:v3.0.0' locally
v3.0.0: Pulling from succinctlabs/sp1-gnark
b3c56a24ca32: Pull complete
0c283a94c958: Pull complete
7587f92130ba: Pull complete
Digest: sha256:98c353f1b3c392d18d1c5f0ea2473c8284b28fd022604f33c195dbb7e99f07f0
Status: Downloaded newer image for ghcr.io/succinctlabs/sp1-gnark:v3.0.0
2024-11-04T12:03:34.069917Z ERROR wrap_plonk_bn254: Failed to run `docker run`: "docker" "run" "--rm" "-v" "/Users/me/.sp1/circuits/plonk/v3.0.0:/circuit" "-v" "/var/folders/g5/y38jzk596376626x304q4j6r0000gn/T/.tmpogGXps:/witness" "-v" "/var/folders/g5/y38jzk596376626x304q4j6r0000gn/T/.tmpshGKJl:/output" "ghcr.io/succinctlabs/sp1-gnark:v3.0.0" "prove" "--system" "plonk" "/circuit" "/witness" "/output"
thread 'main' panicked at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sp1-recursion-gnark-ffi-3.0.0/src/ffi/docker.rs:74:59:
failed to prove with docker: docker command failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-11-04T12:03:34.072564Z  INFO wrap_plonk_bn254: close time.busy=38.8s time.idle=1.88µs
```

Any ideas for what I might be missing or doing wrong?

**Comment by yuwen01** [comment] 2024-11-04 18:41
Are you using the network prover by any chance? Due to some changes between dev and 3.0.0, you can't currently use the latest dev on the network.

**Comment by hu55a1n1** [comment] 2024-11-04 20:14
Thanks for heads up @yuwen01! I was using the local prover with docker. I just applied to get access to the prove network following [these steps](https://docs.succinct.xyz/generating-proofs/prover-network.html). Looking forward. 🙏

**Comment by yuwen01** [comment] 2024-11-04 20:46
I think I might have reproduced the error -- running with `RUST_LOG=info` gives me this

```2024-11-04T20:37:37.449761Z  INFO wrap_bn254: close time.busy=43.6s time.idle=1.55µs
[sp1] plonk circuit artifacts already seem to exist at /home/yuwen/.sp1/circuits/plonk/v3.0.0. if you want to re-download them, delete the directory
2024-11-04T20:37:37.483743Z  INFO wrap_plonk_bn254: Running prove in docker    
20:37:48 ERR error="invalid witness size, got 24292, expected 23846" nbConstraints=10537659
panic: invalid witness size, got 24292, expected 23846
```

**Comment by yuwen01** [comment] 2024-11-05 04:07
Some context from the telegram channel. TLDR generating prod-ready plonk/groth16 proofs on latest dev isn't going to work, since sp1 artifacts are only updated for official releases.

> each sp1 release comes with a set of groth16 and plonk circuit artifacts. These artifacts aren't constantly updated with each new push to dev -- only on each release cycle. You're running into this issue because the circuits and stuff are updated for the latest dev, but the groth16/plonk artifacts are stuck on 3.0.0, which is an incompatibility.
> If you generate proofs using the prover network using that commit then the proof should verify, since the prover network uses entirely 3.0.0 compatible artifacts. If you're interested you can fill out the form here https://forms.gle/rTUvhstS8PFfv9B3A !

> I'll try to release the verifier crate to crates.io tomorrow or wednesday, so hopefully you won't have to wait till 4.0.0

I'll close this issue once the verifier crate is released.

**Comment by yuwen01** [comment] 2024-11-08 00:57
[Verifier crate is up!](https://crates.io/crates/sp1-verifier) Supports docker and network proofs for v3.0.0 circuits.

**Closed by yuwen01** 2024-11-08 00:57 UTC
