### ISSUE TITLE
error: could not compile `syn` (build script) due to 1 previous error

### ISSUE THREAD

**Issue by ava-world** [succinctlabs/sp1#1168] opened 2024-07-24 00:30 UTC
following the official quickstart, i ran into errors trying to generate proofs
while in the ``script`` directory, i ran ``cargo run --release`` and got errors

i am using an ubuntu 20.04 virtual server
![2024-07-19 (2)](https://github.com/user-attachments/assets/7e2197aa-6c4c-46dd-a424-18a289309720)

sp1 was directly downloaded from pre-built binary

**Comment by ava-world** [comment] 2024-07-24 02:09
proof was generated sucessfully using ubuntu 22.04 system and repeating the process that generated the initial errors

![2024-07-24](https://github.com/user-attachments/assets/fb754b30-f68e-4199-92b6-773209491b99)

**Comment by MCJOHN974** [comment] 2024-10-10 06:27
I have very similar error, and my friend could compile my code without any errors, so highly likely the problem is in my setup (like which clang is used, which linker is used, etc). However, I didn't find fix yet

**Comment by nhtyy** [comment] 2024-11-19 23:56
Closing for now as likely outdated, feel free to reopen.

**Closed by nhtyy** 2024-11-19 23:56 UTC
